-
  name: miseki-bitmap
  repository-name: ItMarki/MisekiBitmap
  tag-name:
  asset-configs:
    -
      file-name: licensepack.zip
      copy-list:
        licensepack/LICENSE.txt: LICENSE.txt
        licensepack/MisekiBitmap.ttf: MisekiBitmap.ttf
-
  name: boutique-bitmap-7x7
  repository-name: scott0107000/BoutiqueBitmap7x7
  tag-name:
  asset-configs:
    -
      file-name: BoutiqueBitmap7x7_{version}.zip
      copy-list:
        OFL.txt: LICENSE.txt
        BoutiqueBitmap7x7_{version}.ttf:
-
  name: boutique-bitmap-9x9
  repository-name: scott0107000/BoutiqueBitmap9x9
  tag-name:
  asset-configs:
    -
      file-name: BoutiqueBitmap9x9_{version}.zip
      copy-list:
        OFL.txt: LICENSE.txt
        BoutiqueBitmap9x9_{version}.ttf:
-
  name: cubic-11
  repository-name: ACh-K/Cubic-11
  tag-name:
  asset-configs:
    -
      copy-list:
        Cubic-11-{version}/OFL.txt: LICENSE.txt
        Cubic-11-{version}/fonts/web/Cubic_11.woff2: Cubic_11.woff2
-
  name: galmuri
  repository-name: quiple/galmuri
  tag-name:
  asset-configs:
    -
      file-name: Galmuri-v{version}.zip
      copy-list:
        LICENSE.txt: LICENSE.txt
        Galmuri7.ttf: Galmuri7.ttf
        Galmuri9.ttf: Galmuri9.ttf
        Galmuri11.ttf: Galmuri11.ttf
        GalmuriMono7.ttf: GalmuriMono7.ttf
